# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db_provider:
            entity:
                class: AppBundle\Entity\User
                property: pseudo


    encoders:
        AppBundle\Entity\User: bcrypt




    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            pattern:   ^/
            anonymous: true
            provider: db_provider

            form_login:
                login_path: /login
                check_path: /login
                username_parameter: user_login[pseudo]
                password_parameter: user_login[password]
                
            logout:
                path: /logout
                target: /
            
              
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
            
    #access control:    
    #    {path:"/admin", roles:"ROLE_ADMIN"}